version: '3'

services: 
    server:
        build: ./
        expose:
            - ${PORT}
        enviroment:
            API_HOST: ${HOST}
            APP_SERVER_PORT: ${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/usr/app
        command: npm run dev
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        volumes: ./src/data:/data
